const COMING_SOON = {
"bot-invite":    false,
"join-team":     false,
"force-leave":   false,
"perform-emote": false,
"ban-check":     false,
"player-info":   false,
"visit-spam":    false,
"outfit":        false,
"player-stats":  false,
};
const MAINTENANCE = {
global:          false,
"bot-invite":    false,
"join-team":     false,
"force-leave":   false,
"perform-emote": false,
"ban-check":     false,
"player-info":   false,
"visit-spam":    false,
"outfit":        false,
"player-stats":  false,
};
const FEATURES = [
{ id: "bot-invite",    label: "Bot Invite",    icon: "fa-robot"              },
{ id: "join-team",     label: "Join Tim",       icon: "fa-users"              },
{ id: "force-leave",   label: "Force Leave",    icon: "fa-right-from-bracket" },
{ id: "perform-emote", label: "Perform Emote",  icon: "fa-star"               },
{ id: "ban-check",     label: "Ban Check",      icon: "fa-ban"                },
{ id: "player-info",   label: "Player Info",    icon: "fa-id-card"            },
{ id: "visit-spam",    label: "Visit Spam",     icon: "fa-eye"                },
{ id: "outfit",        label: "Outfit Image",   icon: "fa-shirt"              },
{ id: "player-stats",    label: "Player Stats",    icon: "fa-chart-bar"  },
{ id: "profile-banner", label: "Profile Banner",  icon: "fa-id-badge"   },
];
const REGIONS = [
{ code: "id",     label: "ID",  flag: "id", name: "Indonesia"     },
{ code: "ind",    label: "IND", flag: "in", name: "India"         },
{ code: "na",     label: "NA",  flag: "us",  name: "North America" },
{ code: "bd",     label: "BD",  flag: "bd", name: "Bangladesh"    },
{ code: "sg",     label: "SG",  flag: "sg", name: "Singapore"     },
{ code: "pk",     label: "PK",  flag: "pk", name: "Pakistan"      },
{ code: "br",     label: "BR",  flag: "br", name: "Brazil"        },
{ code: "us",     label: "US",  flag: "us", name: "United States" },
{ code: "sa",     label: "SA",  flag: "sa", name: "Saudi Arabia"  },
{ code: "mea",    label: "MEA", flag: "ae",  name: "Middle East"   },
{ code: "europe", label: "EU",  flag: "eu", name: "Europe"        },
{ code: "tw",     label: "TW",  flag: "tw", name: "Taiwan"        },
{ code: "ru",     label: "RU",  flag: "ru", name: "Russia"        },
{ code: "th",     label: "TH",  flag: "th", name: "Thailand"      },
{ code: "vn",     label: "VN",  flag: "vn", name: "Vietnam"       },
{ code: "kr",     label: "KR",  flag: "kr", name: "Korea"         },
];